- name: download artifact
  get_url:
     url: https://github.com/Anji399/pri/raw/master/target/prime.war
     dest: /tmp
- name: copy artifact
  copy:
     src: /tmp/prime.war
     dest: /opt/tomcat/webapps/prime.war
     owner: tomcat
     group: tomcat
     remote_src: yes
  notify: restart tomcat
 
