- name: download artifact
  get_url:
     url: http://65.1.94.41:8081/repository/prime/
     dest: /tmp
- name: copy artifact
  copy:
     src: /tmp/prime.war
     dest: /opt/tomcat/webapps/prime.war
     owner: tomcat
     group: tomcat
     remote_src: yes
  notify: restart tomcat
 
