- name: download artifact
  get_url:
     url: http://13.235.81.116:8081/repository/prime/
     dest: /usr
- name: copy artifact
  copy:
     src: /usr/prime.war
     dest: /opt/tomcat/webapps/prime.war
     owner: tomcat
     group: tomcat
     remote_src: yes
  notify: restart tomcat
 
